name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Build with Gradle
      env:
        GITHUB_ACTOR: hansi-b
        # this is defined the Github repository settings
        GITHUB_REPO_PAT_RO: ${{ secrets.REPO_PAT_RO }}
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: check jacocoTestReport -PheadlessFxMode=true --info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v6
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
