name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Setup Gradle
      env:
        GITHUB_ACTOR: hansi-b
        # this is defined the Github repository settings
        GITHUB_REPO_PAT_RO: ${{ secrets.REPO_PAT_RO }}
      uses: gradle/actions/setup-gradle@v4.2.0
      with:
        gradle-home-cache-cleanup: true
    - name: Run unit tests
      env:
        GITHUB_ACTOR: hansi-b
        GITHUB_REPO_PAT_RO: ${{ secrets.REPO_PAT_RO }}
      run: ./gradlew check jacocoTestReport -PheadlessFxMode=true --info --build-cache
      continue-on-error: true
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JUnit Test Results
        path: '**/build/test-results/test/TEST-*.xml'
        reporter: java-junit
        fail-on-error: true
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v6
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true